spring:
  application:
    name: kanban
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban
    username: kanban
    password: kanban
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    dev.dsegorov.kanban: DEBUG
    org.springframework.web: INFO